# Generated by Django 3.0.8 on 2020-09-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabClassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chook_up_word', models.CharField(max_length=254, null=True)),
                ('class_type', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=20)),
                ('class_translated', models.CharField(choices=[('Tính từ', 'Tính từ'), ('Trạng từ', 'Trạng từ'), ('Giới từ', 'Giới từ'), ('Danh từ', 'Danh từ'), ('Đại từ', 'Đại từ'), ('Động từ', 'Động từ')], default='Động từ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TabWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_origin', models.CharField(max_length=254, null=True)),
                ('word_translated', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shook_up_word', models.CharField(max_length=254, null=True)),
                ('synonym', models.CharField(max_length=254, null=True)),
                ('word_synonym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.TabWords')),
            ],
        ),
        migrations.CreateModel(
            name='TabSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_up_class', models.CharField(max_length=254, null=True)),
                ('sentence', models.CharField(max_length=254, null=True)),
                ('sentece_translated', models.CharField(max_length=254, null=True)),
                ('class_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.TabClassType')),
            ],
        ),
        migrations.CreateModel(
            name='TabGrammar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ghook_up_word', models.CharField(max_length=254, null=True)),
                ('family_word', models.CharField(max_length=254, null=True)),
                ('word_grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.TabWords')),
            ],
        ),
        migrations.AddField(
            model_name='tabclasstype',
            name='word_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.TabWords'),
        ),
    ]
