# Generated by Django 3.0.8 on 2020-10-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabsentence',
            old_name='sentece_translated',
            new_name='sentence_translated',
        ),
    ]
