# Generated by Django 3.0.8 on 2020-10-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_auto_20201003_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabclasstype',
            old_name='Chook_up_word',
            new_name='word_for_class',
        ),
        migrations.RenameField(
            model_name='tabgrammar',
            old_name='Ghook_up_word',
            new_name='word_for_grammar',
        ),
        migrations.RenameField(
            model_name='tabsentence',
            old_name='hook_up_class',
            new_name='class_for_sentence',
        ),
        migrations.RenameField(
            model_name='tabsynonym',
            old_name='Shook_up_word',
            new_name='word_for_synonym',
        ),
    ]
