# Generated by Django 3.0.8 on 2020-10-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_auto_20201005_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabsentence',
            name='class_for_sentence',
            field=models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TabClassTypeFamilyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_word_for_class', models.CharField(max_length=254, null=True)),
                ('family_word_class_type', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=20, null=True)),
                ('family_word_class_type_translated', models.CharField(choices=[('Tính từ', 'Tính từ'), ('Trạng từ', 'Trạng từ'), ('Giới từ', 'Giới từ'), ('Danh từ', 'Danh từ'), ('Đại từ', 'Đại từ'), ('Động từ', 'Động từ')], default='Động từ', max_length=20)),
                ('family_word_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.TabGrammar')),
            ],
        ),
    ]
