# Generated by Django 3.0.8 on 2020-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_auto_20201012_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabsentence',
            name='word_for_sentence',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
