# Generated by Django 3.0.8 on 2020-11-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_tabsentence_word_for_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabclasstype',
            old_name='class_translated',
            new_name='class_in_vietnamese',
        ),
        migrations.RenameField(
            model_name='tabclasstype',
            old_name='word_class',
            new_name='related_word',
        ),
        migrations.RenameField(
            model_name='tabclasstype',
            old_name='word_for_class',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='tabclasstypefamilyword',
            old_name='family_word_for_class',
            new_name='family_word',
        ),
        migrations.RenameField(
            model_name='tabclasstypefamilyword',
            old_name='family_word_class_type_translated',
            new_name='family_word_class_type_in_vietnamese',
        ),
        migrations.RenameField(
            model_name='tabclasstypefamilyword',
            old_name='family_word_class',
            new_name='related_family_word',
        ),
        migrations.RenameField(
            model_name='tabgrammar',
            old_name='word_grammar',
            new_name='related_word',
        ),
        migrations.RenameField(
            model_name='tabgrammar',
            old_name='word_for_grammar',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='tabsentence',
            old_name='class_for_sentence',
            new_name='class_type',
        ),
        migrations.RenameField(
            model_name='tabsentence',
            old_name='class_sentence',
            new_name='related_class',
        ),
        migrations.RenameField(
            model_name='tabsentence',
            old_name='sentence_translated',
            new_name='sentence_in_vietnamese',
        ),
        migrations.RenameField(
            model_name='tabsentence',
            old_name='word_for_sentence',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='tabsynonym',
            old_name='word_synonym',
            new_name='related_word',
        ),
        migrations.RenameField(
            model_name='tabsynonym',
            old_name='word_for_synonym',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='tabwords',
            old_name='word_origin',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='tabwords',
            old_name='word_translated',
            new_name='word_in_vietnamese',
        ),
    ]
