# Generated by Django 3.0.8 on 2020-11-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_auto_20201124_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_class_you_want_to_delete', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeleteFamilyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_family_word_you_want_to_delete', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeleteSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_sentence_you_want_to_delete', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeleteSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_synonym_you_want_to_delete', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeleteWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_word_you_want_to_delete', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_old_class_to_be_edited', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=20, null=True)),
                ('enter_new_class', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=20, null=True)),
                ('enter_new_class_in_Vietnamese', models.CharField(choices=[('Tính từ', 'Tính từ'), ('Trạng từ', 'Trạng từ'), ('Giới từ', 'Giới từ'), ('Danh từ', 'Danh từ'), ('Đại từ', 'Đại từ'), ('Động từ', 'Động từ')], default='Động từ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EditFamilyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_old_family_word_to_be_edited', models.CharField(max_length=254, null=True)),
                ('enter_new_family_word', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_class_to_find_sentence', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=20, null=True)),
                ('enter_old_sentence_to_be_edited', models.CharField(max_length=254, null=True)),
                ('enter_new_sentence', models.CharField(max_length=254, null=True)),
                ('enter_new_sentence_in_Vietnamese', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_old_synonym_to_be_edited', models.CharField(max_length=254, null=True)),
                ('enter_new_synonym', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindClassByWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_word_to_find_class', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindFamilyWordByWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_word_to_find_family_word', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindSentenceByClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_class_to_find_sentence', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindSentenceByWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_word_to_find_sentence', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindSynonymByWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_word_to_find_synonym', models.CharField(max_length=254, null=True)),
            ],
        ),
    ]
