# Generated by Django 3.0.8 on 2020-11-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_deleteclass_deletefamilyword_deletesentence_deletesynonym_deleteword_editclass_editfamilyword_editse'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_new_word', models.CharField(max_length=254, null=True)),
                ('word_in_Vietnamese', models.CharField(max_length=254, null=True)),
                ('add_class', models.CharField(choices=[('Adjectives', 'Adjectives'), ('Adverbs', 'Adverbs'), ('Prepositions', 'Prepositions'), ('Noun', 'Noun'), ('Pronouns', 'Pronouns'), ('Verbs', 'Verbs')], default='Verbs', max_length=254, null=True)),
                ('class_in_Vietnamese', models.CharField(choices=[('Tính từ', 'Tính từ'), ('Trạng từ', 'Trạng từ'), ('Giới từ', 'Giới từ'), ('Danh từ', 'Danh từ'), ('Đại từ', 'Đại từ'), ('Động từ', 'Động từ')], default='Verbs', max_length=254, null=True)),
                ('enter_a_sentence', models.CharField(max_length=254, null=True)),
                ('sentence_in_Vietnamese', models.CharField(max_length=254, null=True)),
                ('add_family_word', models.CharField(max_length=254, null=True)),
                ('add_synonym', models.CharField(max_length=254, null=True)),
            ],
        ),
    ]
