# Generated by Django 3.0.8 on 2020-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_auto_20201125_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text_to_translate', models.CharField(max_length=254, null=True)),
            ],
        ),
    ]
